name: Build and Test
on:
  pull_request:
    branches:
      - main
  pull_request_target:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.200
      - name: Build with dotnet
        run: dotnet build /warnaserror --configuration Release
      - name: Test with dotnet
        run: dotnet test ./Tests/WitsmlExplorer.Api.Tests/WitsmlExplorer.Api.Tests.csproj --configuration Release

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
        working-directory: ./Src/WitsmlExplorer.Frontend
      - name: Linting
        run: yarn eslint .
        working-directory: ./Src/WitsmlExplorer.Frontend
      - name: Prettier
        run: npx prettier --check .
      - name: Build
        run: yarn build
        working-directory: ./Src/WitsmlExplorer.Frontend
      - name: Test
        run: yarn test
        working-directory: ./Src/WitsmlExplorer.Frontend
